# Uncomment the next line to define a global platform for your project
# platform:ios, '9.0'

target 'WYJKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#pod 'WYJKits'
#  pod 'WYJKits',:path => './WYJKits'
#pod 'PKHUD',:inhibit_warnings => true
pod 'MJRefresh',:inhibit_warnings => true
pod 'DZNEmptyDataSet',:inhibit_warnings => true
pod 'SnapKit',:inhibit_warnings => true
pod 'MBProgressHUD',:inhibit_warnings => true
pod 'Alamofire',:inhibit_warnings => true
#pod 'CaamDau', :git => 'https://gitee.com/CaamDau/CaamDau.git'
pod 'IQKeyboardManagerSwift',:inhibit_warnings => true
pod 'SwiftyRSA'
pod 'SSKeychain'
pod 'LLSegmentViewController'
pod 'JSQMessagesViewController'
end
